:concurrency: <%= Integer(ENV["WORKER_CONCURRENCY"] || 3) %>
:timeout: 60
:verbose: <%= ENV['RAILS_ENV'] != 'production' %>
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
